# Generated by Django 3.1.2 on 2020-10-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent',
            name='issuperuser',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
